### PR TITLE
Added Swift-version

### PR DESCRIPTION
**Pull request by fruitcoder**
I just added my files in a folder, without changing the original project. The commit contains a single project with all the files.

### CODE REVIEW

**Comment by dusi** [comment]
I'll try to review as soon as possible!

**Comment by fruitcoder** [comment]
Thank you, just tell my how I should restructure the code/project if you want any changes!

**Comment by dusi** [comment]
@fruitcoder just a quick heads up...I've been investigating how to best deal with this and think I'm going to do the following:
1. Rewrite the whole thing in Swift (taking your files into account) on the Swift branch
2. use language specifics (structs, generics, etc.)
3. Remove prefixes
4. Rename PADTiltViewController to TiltViewController in order to loose the prefix here as well
5. Add a new section to README with contributors where I'd like to include you for the work you've done

Any other ideas? I really wanted to make sure this will feel like a Swift library rather than just changing language. Since I'm going to be changing the name any ideas here? I still think TiltViewController isn't juicy enough :)

**Comment by fruitcoder** [comment]
Your approach seams very reasonable. Of course, I didn't take certain language specifics of Swift into account. 
I am looking very forward to the final result!
I am not so create when it comes to naming, but out of the top of my head maybe:
TiltFlow, TiltControl, TiltScrollControl 
This is from abstract to concrete, and since the TiltViewController is not a big framework, it might make sense to be more concrete. 
But that's up to you. 
Keep me updated!

**Pull request closed without merging**
